CREATE TABLE IF NOT EXISTS users (
  _id CHAR(24) PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  profile JSON NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  emailVerified TINYINT(1) NOT NULL DEFAULT 0,
  emailVerifyToken VARCHAR(128) NULL,
  emailVerifyExpires DATETIME NULL,
  passwordResetToken VARCHAR(128) NULL,
  passwordResetExpires DATETIME NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'approved',
  approvedAt DATETIME NULL,
  approvedBy VARCHAR(100) NULL,
  rejectedReason VARCHAR(200) NULL,
  rejectedAt DATETIME NULL,
  rejectedBy VARCHAR(100) NULL,
  lastLogin DATETIME NULL,
  loginAttempts INT NOT NULL DEFAULT 0,
  lockUntil DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_status_created (status, createdAt),
  INDEX idx_users_active_created (isActive, createdAt)
);

CREATE TABLE IF NOT EXISTS announcements (
  _id CHAR(24) PRIMARY KEY,
  text VARCHAR(200) NOT NULL,
  lang VARCHAR(10) NOT NULL DEFAULT 'zh',
  `order` INT NOT NULL DEFAULT 0,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_announcements_public (lang, isActive, `order`, createdAt)
);

CREATE TABLE IF NOT EXISTS inventory_files (
  _id CHAR(24) PRIMARY KEY,
  dataType VARCHAR(30) NOT NULL DEFAULT 'emission',
  title VARCHAR(120) NOT NULL,
  datasetKey VARCHAR(80) NOT NULL DEFAULT '',
  datasetName VARCHAR(160) NOT NULL DEFAULT '',
  description VARCHAR(500) NOT NULL DEFAULT '',
  originalFilename VARCHAR(255) NOT NULL,
  storedFilename VARCHAR(255) NOT NULL,
  relativePath VARCHAR(500) NOT NULL,
  mimeType VARCHAR(120) NOT NULL DEFAULT 'application/octet-stream',
  extension VARCHAR(20) NOT NULL DEFAULT 'tif',
  size BIGINT NOT NULL DEFAULT 0,
  pollutant VARCHAR(40) NOT NULL DEFAULT '',
  year VARCHAR(10) NOT NULL DEFAULT '',
  category VARCHAR(80) NOT NULL DEFAULT '',
  subject VARCHAR(120) NOT NULL DEFAULT '',
  period VARCHAR(40) NOT NULL DEFAULT '',
  scale VARCHAR(30) NOT NULL DEFAULT 'annual',
  version VARCHAR(40) NOT NULL DEFAULT 'v1',
  developer VARCHAR(120) NOT NULL DEFAULT '',
  metadata JSON NULL,
  isPublished TINYINT(1) NOT NULL DEFAULT 0,
  downloadCount INT NOT NULL DEFAULT 0,
  uploadedBy CHAR(24) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_inventory_public (dataType, datasetKey, isPublished, year, category, updatedAt),
  FULLTEXT INDEX ft_inventory (title, datasetName, description, pollutant, subject, originalFilename)
);

CREATE TABLE IF NOT EXISTS download_histories (
  _id CHAR(24) PRIMARY KEY,
  user CHAR(24) NULL,
  username VARCHAR(80) NOT NULL DEFAULT '',
  email VARCHAR(120) NOT NULL DEFAULT '',
  dataType VARCHAR(30) NOT NULL DEFAULT 'emission',
  dataTypeLabel VARCHAR(80) NOT NULL DEFAULT '',
  datasetKey VARCHAR(80) NOT NULL DEFAULT '',
  datasetName VARCHAR(160) NOT NULL DEFAULT '',
  downloadType VARCHAR(20) NOT NULL DEFAULT 'single',
  filename VARCHAR(255) NOT NULL,
  filePath VARCHAR(500) NOT NULL DEFAULT '',
  fileCount INT NOT NULL DEFAULT 1,
  fileSize BIGINT NOT NULL DEFAULT 0,
  year VARCHAR(10) NOT NULL DEFAULT '',
  category VARCHAR(80) NOT NULL DEFAULT '',
  subject VARCHAR(120) NOT NULL DEFAULT '',
  scale VARCHAR(30) NOT NULL DEFAULT '',
  filters JSON NULL,
  inventoryId CHAR(24) NULL,
  ip VARCHAR(80) NOT NULL DEFAULT '',
  userAgent VARCHAR(500) NOT NULL DEFAULT '',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_download_user_created (user, createdAt),
  INDEX idx_download_dataset_created (dataType, datasetKey, createdAt)
);
